version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  producer-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-tier
    ports:
      - "7198:80"