version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  producer-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-tier
    ports:
      - "5123:80"