version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    networks:
      - app-tier
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    networks:
      - app-tier
    ports:
      - "9092:9092"
    volumes:
      - /tmp/kafka-persistence/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  producer-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-tier
    ports:
      - "5123:80"
    depends_on:
      - zookeeper
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local